name: carsales

dependencies:
  - python=3.11
  - pip:
    - seleniumbase
    - streamlit
    - numpy
    - attrs
    - pandas
    - plotly
    - pip
    - matplotlib
    - watchdog
    - undetected-chromedriver
    - webdriver-manager
